package pages;

import org.apache.commons.lang3.RandomStringUtils;
import org.openqa.selenium.By;
import utils.Utils;

public class RegistrationPage {

    private static final By SURNAME = By.id("firstname");
    private static final By NAME = By.id("lastname");
    private static final By EMAIL_ADDRESS = By.id("email_address");
    private static final By PASSWORD = By.id("password");
    private static final By PASSWORD_CONFIRM = By.id("confirmation");
    private static final By GO_BUTTON = By.xpath("//*[@id='form-validate']/div[3]/button");
    private static final By VALIDATION_ADVICE = By.id("advice-validate-cpassword-confirmation");
    private static final By SURNAME_ADVICE = By.id("advice-required-entry-firstname");
    private static final By NAME_ADVICE = By.id("advice-required-entry-lastname");
    private static final By EMAIL_ADVICE = By.id("advice-required-entry-email_address");
    private static final By PASSWORD_ADVICE = By.id("advice-required-entry-password");
    private static final By PASSWORD_ADVICE2 = By.id("advice-required-entry-confirmation");


    public static void registration(String surname, String name, String email, String password1, String password2){
        HomePage.navigateToLoginPage();
        Utils.click(LoginPage.REGISTRATION_BUTTON);
        Utils.writeText(SURNAME, surname);
        Utils.writeText(NAME, name);
        Utils.writeText(EMAIL_ADDRESS, email);
        Utils.writeText(PASSWORD, password1);
        Utils.writeText(PASSWORD_CONFIRM, password2);
        Utils.click(GO_BUTTON);
    }

    public static String autoGeneratedSurname(){
        String surname = RandomStringUtils.randomAlphabetic(8);
        return surname;
    }

    public static String autoGeneratedName(){
        String name = RandomStringUtils.randomAlphabetic(8);
        return name;
    }

    public static String autoGeneratedEmail(){
        String generatedstring = RandomStringUtils.randomAlphabetic(8);
        String email = generatedstring+"@gmail.com";
        return email;
    }

    public static String autoGeneratedPassword1(){
        String password1 = RandomStringUtils.randomAlphabetic(8);
        return password1;
    }

    public static String autoGeneratedPassword2(){
        String password2 = RandomStringUtils.randomAlphabetic(8);
        return password2;
    }

    public static String validationPWConfMsg(){
        String validationPWConfMsg = Utils.getText(VALIDATION_ADVICE);
        return validationPWConfMsg;
    }

    public static String validationSurnameMsg(){
        String validationSurnameMsg = Utils.getText(SURNAME_ADVICE);
        return validationSurnameMsg;
    }

    public static String validationNameMsg(){
        String validationNameMsg = Utils.getText(NAME_ADVICE);
        return validationNameMsg;
    }

    public static String validationEmailMsg(){
        String validationEmailMsg = Utils.getText(EMAIL_ADVICE);
        return validationEmailMsg;
    }

    public static String validationPWMsg(){
        String validationPWMsg = Utils.getText(PASSWORD_ADVICE);
        return validationPWMsg;
    }

    public static String validationPW2Msg(){
        String validationPW2Msg = Utils.getText(PASSWORD_ADVICE2);
        return validationPW2Msg;
    }
}